sudo: required
language: java
jdk: oraclejdk8

# addons: 
#   sonarcloud: 
#     organization: maheshdevelopments-github
#     token: 
#       secure: 3d89103adef0293768ed92476aadf23f51312b14

before_install:
- chmod +x mvnw

script:
- "./mvnw clean install -B"
# - "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"

cache:
  directories:
  - "$HOME/.m2/repository"
  # - "$HOME/.sonar/cache"